version: '3'

services:

  web:
    build:
      context:
        ./prof_web
    volumes:
      - ./prof_web:/app
      - /home/ubuntu/prof_web/dev/prof_web/media:/app/media
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    container_name: nginx2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/prof_web/dev/prof_web/media:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
